import {
  JobApplication,
  ApplicationEvent,
  Interview,
  ApplicationDocument,
  NotificationItem,
  UserSettings,
} from '../types';

export const DEFAULT_USER_SETTINGS: UserSettings = {
  theme: 'system',
  in_app_notifications: true,
  notify_interview: true,
  notify_deadline: true,
  notify_followup: true,
  notify_expired: true,
  whatsapp_enabled: false,
  whatsapp_phone: '+6281234567890',
  whatsapp_notification_types: {
    interview: true,
    deadline: true,
    followup: true,
    expired: true,
  },
  currency_default: 'USD',
};

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-001',
    company: 'PT GoTo Gojek Tokopedia',
    position: 'Senior Data Analyst',
    location: 'Jakarta, Indonesia',
    work_type: 'Hybrid',
    employment_type: 'Full-time',
    job_url: 'https://careers.goto.com/jobs/data-analyst-senior',
    application_date: '2026-08-18',
    deadline: '2026-08-30',
    salary_min: 22000000,
    salary_max: 28000000,
    salary_currency: 'IDR',
    status: 'HR Interview',
    source: 'LinkedIn',
    recruiter_name: 'Sarah Wijaya',
    recruiter_contact: 'sarah.wijaya@goto.com',
    notes: 'Recruiter reached out on LinkedIn. Team is scaling Merchant Analytics. Mentioned strong SQL & BigQuery focus.',
    created_at: '2026-08-18T09:30:00Z',
    updated_at: '2026-08-22T14:15:00Z',
  },
  {
    id: 'app-002',
    company: 'Traveloka',
    position: 'Lead Frontend Engineer',
    location: 'BSD City, Tangerang',
    work_type: 'Hybrid',
    employment_type: 'Full-time',
    job_url: 'https://traveloka.com/careers/lead-frontend',
    application_date: '2026-08-10',
    deadline: '2026-08-25',
    salary_min: 30000000,
    salary_max: 38000000,
    salary_currency: 'IDR',
    status: 'Technical Test',
    source: 'Company Website',
    recruiter_name: 'Dimas Pratama',
    recruiter_contact: 'dimas.p@traveloka.com',
    notes: 'Take-home technical test submitted on React performance optimization and microfrontends. Awaiting review.',
    created_at: '2026-08-10T11:00:00Z',
    updated_at: '2026-08-23T10:00:00Z',
  },
  {
    id: 'app-003',
    company: 'Stripe',
    position: 'Solutions Engineer (APAC)',
    location: 'Singapore (Remote eligible)',
    work_type: 'Remote',
    employment_type: 'Full-time',
    job_url: 'https://stripe.com/jobs/solutions-engineer-apac',
    application_date: '2026-08-05',
    deadline: '2026-08-28',
    salary_min: 6500,
    salary_max: 8500,
    salary_currency: 'USD',
    status: 'Interview',
    source: 'Referral',
    recruiter_name: 'Chloe Bennett',
    recruiter_contact: 'cbennett@stripe.com',
    notes: 'Referred by Alex from Tech Lead team. System architecture & client communication round coming up.',
    created_at: '2026-08-05T08:00:00Z',
    updated_at: '2026-08-24T09:00:00Z',
  },
  {
    id: 'app-004',
    company: 'PT Bank Central Asia (BCA)',
    position: 'Senior Full Stack Developer',
    location: 'Jakarta Barat',
    work_type: 'On-site',
    employment_type: 'Full-time',
    job_url: 'https://karir.bca.co.id/posisi/fullstack',
    application_date: '2026-07-28',
    deadline: '2026-08-15',
    salary_min: 25000000,
    salary_max: 32000000,
    salary_currency: 'IDR',
    status: 'Offer',
    source: 'JobStreet',
    recruiter_name: 'Budi Santoso',
    recruiter_contact: 'budi_santoso@bca.co.id',
    notes: 'Offer letter received! Base salary IDR 29M + 14-month bonus + medical insurance tier A. Decision deadline Sep 1.',
    created_at: '2026-07-28T14:20:00Z',
    updated_at: '2026-08-24T16:00:00Z',
  },
  {
    id: 'app-005',
    company: 'Shopee',
    position: 'Product Operations Specialist',
    location: 'Jakarta Selatan',
    work_type: 'Hybrid',
    employment_type: 'Full-time',
    job_url: 'https://careers.shopee.co.id/jobs/prod-ops',
    application_date: '2026-08-20',
    deadline: '2026-09-05',
    salary_min: 15000000,
    salary_max: 19000000,
    salary_currency: 'IDR',
    status: 'Screening',
    source: 'Glints',
    recruiter_name: 'Amanda Lestari',
    recruiter_contact: 'amanda.l@shopee.com',
    notes: 'CV viewed by hiring manager. Initial phone screening expected this week.',
    created_at: '2026-08-20T10:15:00Z',
    updated_at: '2026-08-21T08:30:00Z',
  },
  {
    id: 'app-006',
    company: 'Bukalapak',
    position: 'Staff Platform Engineer',
    location: 'Jakarta Selatan',
    work_type: 'Remote',
    employment_type: 'Full-time',
    job_url: 'https://careers.bukalapak.com/staff-platform',
    application_date: '2026-08-22',
    deadline: '2026-09-10',
    salary_min: 35000000,
    salary_max: 45000000,
    salary_currency: 'IDR',
    status: 'Applied',
    source: 'LinkedIn',
    recruiter_name: 'Faisal Akbar',
    recruiter_contact: 'faisal.recruiting@bukalapak.com',
    notes: 'Applied with tailored DevOps/Kubernetes portfolio and tailored cover letter.',
    created_at: '2026-08-22T13:00:00Z',
    updated_at: '2026-08-22T13:00:00Z',
  },
  {
    id: 'app-007',
    company: 'Canva',
    position: 'Senior UI/UX Engineer',
    location: 'Sydney (Remote)',
    work_type: 'Remote',
    employment_type: 'Full-time',
    job_url: 'https://canva.com/careers/ux-engineer',
    application_date: '2026-08-24',
    deadline: '2026-09-15',
    salary_min: 7000,
    salary_max: 9000,
    salary_currency: 'USD',
    status: 'Wishlist',
    source: 'Company Website',
    recruiter_name: 'Jessica Taylor',
    recruiter_contact: '',
    notes: 'Need to polish Figma plugin showcase and prepare design token documentation before applying.',
    created_at: '2026-08-24T07:45:00Z',
    updated_at: '2026-08-24T07:45:00Z',
  },
  {
    id: 'app-008',
    company: 'Grab Holdings',
    position: 'Data Engineering Lead',
    location: 'Jakarta',
    work_type: 'Hybrid',
    employment_type: 'Full-time',
    job_url: 'https://grab.careers/job/data-eng-lead',
    application_date: '2026-07-10',
    deadline: '2026-07-25',
    salary_min: 38000000,
    salary_max: 48000000,
    salary_currency: 'IDR',
    status: 'Expired',
    source: 'LinkedIn',
    recruiter_name: 'Kevin Tan',
    recruiter_contact: 'kevin.tan@grabtaxi.com',
    notes: 'Job listing closed and deadline elapsed with no response after preliminary intake.',
    created_at: '2026-07-10T09:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'app-009',
    company: 'Netflix APAC',
    position: 'Full Stack Infrastructure Engineer',
    location: 'Singapore',
    work_type: 'Remote',
    employment_type: 'Full-time',
    job_url: 'https://jobs.netflix.com/jobs/fs-infra',
    application_date: '2026-07-02',
    deadline: '2026-07-20',
    salary_min: 9000,
    salary_max: 12000,
    salary_currency: 'USD',
    status: 'Rejected',
    source: 'Company Website',
    recruiter_name: 'Marcus Vance',
    recruiter_contact: 'mvance@netflix.com',
    notes: 'Position placed on hiring pause for regional team restructuring. Warm feedback received.',
    created_at: '2026-07-02T11:00:00Z',
    updated_at: '2026-07-25T15:00:00Z',
  },
];

export const INITIAL_EVENTS: ApplicationEvent[] = [
  {
    id: 'evt-001',
    application_id: 'app-001',
    title: 'Application Submitted',
    description: 'Submitted application on LinkedIn with Data Analyst Resume v4.',
    event_type: 'status_change',
    event_date: '2026-08-18T09:30:00Z',
    created_at: '2026-08-18T09:30:00Z',
  },
  {
    id: 'evt-002',
    application_id: 'app-001',
    title: 'Recruiter Contacted',
    description: 'Sarah Wijaya emailed requesting an introductory call.',
    event_type: 'contact',
    event_date: '2026-08-20T11:00:00Z',
    created_at: '2026-08-20T11:00:00Z',
  },
  {
    id: 'evt-003',
    application_id: 'app-001',
    title: 'HR Screening Call Scheduled',
    description: 'Confirmed HR Interview for August 26, 2026 at 10:00 AM WIB.',
    event_type: 'interview',
    event_date: '2026-08-22T14:15:00Z',
    created_at: '2026-08-22T14:15:00Z',
  },
  {
    id: 'evt-004',
    application_id: 'app-002',
    title: 'Take-home Test Received',
    description: 'Received Traveloka Frontend Challenge: Web Performance optimization.',
    event_type: 'deadline',
    event_date: '2026-08-19T08:00:00Z',
    created_at: '2026-08-19T08:00:00Z',
  },
  {
    id: 'evt-005',
    application_id: 'app-002',
    title: 'Technical Test Submitted',
    description: 'GitHub repository link sent to Dimas Pratama.',
    event_type: 'status_change',
    event_date: '2026-08-23T10:00:00Z',
    created_at: '2026-08-23T10:00:00Z',
  },
  {
    id: 'evt-006',
    application_id: 'app-003',
    title: 'Technical Round Scheduled',
    description: 'Solutions Engineering deep dive with APAC Lead.',
    event_type: 'interview',
    event_date: '2026-08-24T09:00:00Z',
    created_at: '2026-08-24T09:00:00Z',
  },
  {
    id: 'evt-007',
    application_id: 'app-004',
    title: 'Final Offer Letter Received',
    description: 'Official offer package IDR 29,000,000 / month gross.',
    event_type: 'status_change',
    event_date: '2026-08-24T16:00:00Z',
    created_at: '2026-08-24T16:00:00Z',
  },
];

export const INITIAL_INTERVIEWS: Interview[] = [
  {
    id: 'int-001',
    application_id: 'app-001',
    type: 'HR Interview',
    scheduled_at: '2026-08-26T10:00:00+07:00',
    duration_minutes: 45,
    interviewer: 'Sarah Wijaya (Talent Partner)',
    meeting_url: 'https://meet.google.com/xyz-goto-hr',
    location: 'Google Meet',
    notes: 'Review career history, salary expectations (IDR 24-28M), and motivation for GoTo Merchant Platform.',
    questions: [
      'Tell me about your transition into data analytics.',
      'How do you manage conflicting metric requirements between Product and Business teams?',
      'What are your compensation expectations?',
    ],
    result: 'Pending',
    created_at: '2026-08-22T14:15:00Z',
    updated_at: '2026-08-22T14:15:00Z',
  },
  {
    id: 'int-002',
    application_id: 'app-003',
    type: 'Technical Interview',
    scheduled_at: '2026-08-27T14:00:00+07:00',
    duration_minutes: 60,
    interviewer: 'Michael Zhao (Staff Solutions Architect)',
    meeting_url: 'https://stripe.zoom.us/j/9876543210',
    location: 'Zoom',
    notes: 'Focus on Stripe Connect webhooks, idempotency, API security, and merchant onboarding flow.',
    questions: [
      'Walk me through designing an idempotent webhook listener for payment intents.',
      'How would you diagnose a sudden 5xx error spike on customer checkout sessions?',
      'Explain difference between Destination Charges and Separate Charges & Transfers.',
    ],
    result: 'Pending',
    created_at: '2026-08-24T09:00:00Z',
    updated_at: '2026-08-24T09:00:00Z',
  },
  {
    id: 'int-003',
    application_id: 'app-004',
    type: 'User Interview',
    scheduled_at: '2026-08-14T11:00:00+07:00',
    duration_minutes: 60,
    interviewer: 'Ir. Hendra Gunawan (VP Technology BCA)',
    meeting_url: 'https://teams.microsoft.com/l/meetup-join/bca-tech',
    location: 'Menara BCA Grand Indonesia / MS Teams',
    notes: 'Discussion went very smoothly. Discussed legacy migration to modern React micro-frontends and security compliance.',
    questions: [
      'How do you ensure zero data leak in high-throughput banking transaction logs?',
      'How would you lead junior developers transitioning from Monolith to Event-Driven services?',
    ],
    result: 'Passed',
    created_at: '2026-08-10T10:00:00Z',
    updated_at: '2026-08-16T15:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: ApplicationDocument[] = [
  {
    id: 'doc-001',
    application_id: 'app-001',
    name: 'CV_Data_Analyst_GoTo_v4.pdf',
    type: 'CV',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: 245000,
    mime_type: 'application/pdf',
    uploaded_at: '2026-08-18T09:35:00Z',
    content_text: `# Senior Data Analyst Curriculum Vitae\n\n**Candidate:** Professional Data & Analytics Specialist\n**Email:** applicant.pro@example.com | **Phone:** +62 812-3456-7890\n**Location:** Jakarta, Indonesia\n\n## Professional Summary\nData Analyst with 5+ years of experience leading business intelligence, funnel conversion analysis, and predictive modeling for high-scale e-commerce and fintech platforms. Expert in SQL, Python, BigQuery, Tableau, and dbt.\n\n## Key Achievements\n- Boosted merchant retention rate by 14% through dynamic cohort churn modeling.\n- Designed automated ETL pipelines processing 10M+ daily events.\n- Created executive dashboards used by C-suite stakeholders for weekly GMV reviews.\n\n## Technical Skills\n- **Languages:** SQL, Python (Pandas, Scikit-Learn, PySpark), R\n- **Databases & Warehousing:** BigQuery, Snowflake, PostgreSQL, ClickHouse\n- **BI Tools:** Tableau, Metabase, Looker, Power BI`,
  },
  {
    id: 'doc-002',
    application_id: 'app-001',
    name: 'Cover_Letter_GoTo_Merchant.pdf',
    type: 'Cover Letter',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: 112000,
    mime_type: 'application/pdf',
    uploaded_at: '2026-08-18T09:36:00Z',
    content_text: `# Cover Letter - PT GoTo Gojek Tokopedia\n\n**To:** Talent Acquisition Team, GoTo Merchant Platform\n**Subject:** Application for Senior Data Analyst\n\nDear Hiring Team,\n\nI am writing to express my enthusiastic interest in the Senior Data Analyst role at GoTo. Having followed GoTo's relentless empowerment of Indonesian MSMEs through the integrated Gojek and Tokopedia ecosystem, I am excited about the opportunity to contribute data-driven insights to accelerate merchant growth.\n\nWith extensive experience architecting automated SQL pipelines and designing merchant segmentation algorithms, I am confident in my ability to immediately deliver value to your analytics organization.\n\nThank you for your consideration. I look forward to discussing how my experience aligns with your team's vision.\n\nWarm regards,\nApplicant`,
  },
  {
    id: 'doc-003',
    application_id: 'app-001',
    name: 'Job_Description_GoTo_Senior_Analyst.pdf',
    type: 'Job Description',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: 180000,
    mime_type: 'application/pdf',
    uploaded_at: '2026-08-18T09:37:00Z',
    content_text: `# Job Description: Senior Data Analyst - Merchant Platform\n\n**Company:** PT GoTo Gojek Tokopedia Tbk\n**Location:** Jakarta (Hybrid)\n**Level:** Senior / Lead IC\n\n### Responsibilities\n- Partner with Product Managers and Engineering Leads to define North Star metrics and OKRs for Merchant Analytics.\n- Build robust data models in Google BigQuery to power real-time merchant reporting.\n- Conduct deep-dive root cause analysis on drop-offs, payment settlement delays, and onboarding bottlenecks.\n\n### Requirements\n- 4+ years of data analytics experience in tech / e-commerce.\n- Exceptional fluency with advanced SQL (window functions, CTEs, query optimization).\n- Strong storytelling ability with data visualization tools (Tableau/Looker).`,
  },
  {
    id: 'doc-004',
    application_id: 'app-002',
    name: 'Traveloka_Frontend_Challenge_Summary.pdf',
    type: 'Portfolio',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: 450000,
    mime_type: 'application/pdf',
    uploaded_at: '2026-08-23T10:05:00Z',
    content_text: `# Technical Challenge Submission: Web Performance Optimization\n\n**Candidate:** Frontend Architect\n**Target:** Traveloka Flight Booking Experience\n\n## Overview\nThis submission demonstrates Core Web Vitals optimization techniques reducing Largest Contentful Paint (LCP) from 3.8s to 1.1s and Cumulative Layout Shift (CLS) to 0.01.\n\n## Key Architectural Decisions\n1. Implemented streaming SSR with React Suspense.\n2. Asset preloading for critical flight search hero assets.\n3. Virtualized list rendering for 500+ flight inventory items.\n4. Service Worker caching strategy for offline route details.`,
  },
  {
    id: 'doc-005',
    application_id: 'app-004',
    name: 'BCA_Official_Offer_Letter.pdf',
    type: 'Certificate',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: 320000,
    mime_type: 'application/pdf',
    uploaded_at: '2026-08-24T16:05:00Z',
    content_text: `# Employment Offer Letter - PT Bank Central Asia Tbk\n\n**Date:** August 24, 2026\n**Candidate:** Senior Full Stack Developer\n**Department:** Enterprise Banking Solutions (IT Div)\n\nWe are pleased to offer you the position of Senior Full Stack Developer. Below is a summary of your terms of employment:\n\n- **Base Salary:** IDR 29,000,000 per month (Gross)\n- **Annual Bonus:** Performance bonus target 2.5 - 4.0 months salary\n- **Medical Coverage:** Full executive outpatient & hospitalization\n- **Start Date:** October 1, 2026\n\nPlease sign and return by September 1, 2026.`,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    title: 'Upcoming HR Interview',
    message: 'HR Interview with PT GoTo Gojek Tokopedia (Sarah Wijaya) on Aug 26, 10:00 AM.',
    type: 'interview_reminder',
    application_id: 'app-001',
    event_date: '2026-08-26T10:00:00+07:00',
    is_read: false,
    created_at: '2026-08-24T10:00:00Z',
  },
  {
    id: 'notif-002',
    title: 'Technical Interview Approaching',
    message: 'Solutions Engineering deep dive with Stripe on Aug 27, 2:00 PM WIB.',
    type: 'interview_reminder',
    application_id: 'app-003',
    event_date: '2026-08-27T14:00:00+07:00',
    is_read: false,
    created_at: '2026-08-24T12:00:00Z',
  },
  {
    id: 'notif-003',
    title: 'Application Deadline Tomorrow',
    message: 'Application deadline for Traveloka (Lead Frontend Engineer) is tomorrow, Aug 25.',
    type: 'deadline_reminder',
    application_id: 'app-002',
    event_date: '2026-08-25',
    is_read: false,
    created_at: '2026-08-24T08:00:00Z',
  },
  {
    id: 'notif-004',
    title: 'Offer Decision Pending',
    message: 'PT Bank Central Asia (BCA) offer letter response requested by Sep 1, 2026.',
    type: 'followup_reminder',
    application_id: 'app-004',
    event_date: '2026-09-01',
    is_read: true,
    created_at: '2026-08-24T16:30:00Z',
  },
  {
    id: 'notif-005',
    title: 'Application Expired',
    message: 'Grab Holdings (Data Engineering Lead) deadline has elapsed with no active status update.',
    type: 'application_expired',
    application_id: 'app-008',
    is_read: true,
    created_at: '2026-08-01T10:00:00Z',
  },
];
